services:
  # Backend API service
  - type: web
    name: urohealth-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://clinic_admin:adminMuchai123@cluster0.jrm4jes.mongodb.net/clinic_management?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: UroHealthSecureJWTSecret2024
      - key: PORT
        value: 10000
    healthCheckPath: /
