services:
  # Backend API service
  - type: web
    name: urohealth-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false # This should be set in the Render dashboard
      - key: JWT_SECRET
        sync: false # This should be set in the Render dashboard
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
