services:
  # Backend API service
  - type: web
    name: clinic-management-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://clinic_admin:adminMuchai123@cluster0.jrm4jes.mongodb.net/clinic_management?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: UroHealthSecureJWTSecret2024
      - key: PORT
        value: 10000
    healthCheckPath: /

  # Frontend static site
  - type: web
    name: clinic-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://clinic-management-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
